import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { MyNavigationMenu } from "@/components/navigation-menu";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-dvh`}
      >
        <main className="h-full">
          <Toaster />
          <MyNavigationMenu />
          {children}
        </main>
      </body>
    </html>
  );
}
